# Generated by Django 5.1.6 on 2025-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='item',
            name='current_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
