"""
Django settings for auction_web project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
from dotenv import load_dotenv

# Tìm đến file .env và đọc các biến trong đó vào môi trường
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w-t8l2+f*=gt(0%&^_+hrzbuf46)tbm@^79#ngcxt^sn9*^wz)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',

    # Ứng dụng bên thứ ba
    'rest_framework',
    'rest_framework_simplejwt',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Ứng dụng của project 
    'apps.auth_users.apps.AuthUsersConfig',
    'apps.items.apps.ItemsConfig',
    'apps.bidding.apps.BiddingConfig',
    'apps.payments.apps.PaymentsConfig',
    'apps.reviews.apps.ReviewsConfig',
    'apps.wallet.apps.WalletConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]


# Cấu hình CORS (QUAN TRỌNG!)
# Cho phép frontend của anh (chạy ở domain khác) gọi API
# Trong môi trường development, có thể cho phép tất cả:
CORS_ALLOW_ALL_ORIGINS = True 
# Khi deploy lên production, phải cấu hình cụ thể hơn:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000", # Nếu frontend React/Vue chạy ở port 3000
#     "http://127.0.0.1:3000",
#     "https://your-frontend-domain.com", # Domain frontend của anh khi deploy
# ]

ROOT_URLCONF = 'auction_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'auction_web/templates'],  # Thư mục chứa các template của project
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auction_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Sử dụng PostgreSQL
        'NAME': 'auctiondb',
        'USER': 'root',
        'PASSWORD': '1447928479',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'auction_web/static',  # Thư mục chứa các file tĩnh chính của project
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'auth_users.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tvhoangg05@gmail.com'  
EMAIL_HOST_PASSWORD = 'aabc ijil fyzu vzkx'  

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', # <--- THÊM CÁI NÀY VÀO ĐÂY!
        'rest_framework_simplejwt.authentication.JWTAuthentication', # Giữ lại nếu anh CÓ DÙNG JWT ở chỗ khác
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Bắt buộc đăng nhập cho mọi API mặc định
        'rest_framework.permissions.IsAuthenticatedOrReadOnly', # Cho phép xem nếu chưa đăng nhập, sửa/xóa phải đăng nhập
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

ACCOUNT_FORMS = {'signup': 'apps.auth_users.forms.CustomSignupForm'}
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_LOGIN_METHODS = {"email"}  # Chỉ cho phép đăng nhập bằng email
ACCOUNT_UNIQUE_EMAIL = True  # Email duy nhất
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Bắt buộc xác thực email
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True  # Chuyển hướng sau khi đăng nhập thành công



# Các trường trong form đăng ký
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    
    "password1*",
    "password2*"
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],  # Quyền truy cập
        'AUTH_PARAMS': {'access_type': 'online'},  # Loại xác thực
        'APP': {
            'client_id': '', 
            'secret': '',
            'key': ''
        }
    }
}

# VietQR API Configuration
VIETQR_CLIENT_ID = "99fb5419-7a77-4cb1-9ca4-81e92b979853"
VIETQR_API_KEY = "cf6ddc52-67c5-4bf4-9210-a2f3ab5183dd"
VIETQR_GENERATE_API_URL = "https://api.vietqr.io/v2/generate"

WEBSITE_BANK_ACCOUNT_NO = "0606062005"       
WEBSITE_BANK_ACCOUNT_NAME = "TRAN QUANG HUY" 
WEBSITE_BANK_ACQ_ID = "970443"     
