# Generated by Django 5.1.6 on 2025-03-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_item_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
