# Generated by Django 5.1.7 on 2025-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ xử lý'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy')], default='PENDING', help_text='Trạng thái giao dịch', max_length=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Nạp tiền'), ('WITHDRAWAL', 'Rút tiền'), ('PURCHASE_PAYMENT', 'Thanh toán mua hàng'), ('SALE_RECEIVED', 'Nhận tiền bán hàng')], default='DEPOSIT', help_text='Loại giao dịch', max_length=20),
        ),
    ]
