# Generated by Django 5.1.6 on 2025-04-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviews',
            table='reviews',
        ),
    ]
